// Car Brands
import Audi from "../assets/audiLogo.png";
import VW from "../assets/VWLogo.png";
import BMW from "../assets/BMW.png";
import Toyota from "../assets/Toyota.png";
import Ford from "../assets/Ford.png";
import Mercedes from "../assets/Mercedes-Benz.png";
import Volvo from "../assets/Volvo.png";
import Skoda from "../assets/Skoda.png";
import Vauxhall from "../assets/Vauxhall.png";
import Honda from "../assets/Honda.png";
import Seat from "../assets/Seat.png";
import Cupra from "../assets/Cupra.png";

// Car Images
import Q4_e_tron from "../assets/audi_q4_e-tron.jpg";
import TTRS_2023 from "../assets/TTRS_2023.jpg";
import TTS_2021 from "../assets/TTS_2021.jpg";
import RS7_2023 from "../assets/RS7_2023.jpg";

//Car Details
import electric from "../assets/electric.png";
import fuel from "../assets/fuel.png";

type carsDataType = {
	id: number;
	make: string;
	year: string;
	src: string;
	imgSize: "sm" | "md" | "lg";
	models: any;
};

export const carsData: carsDataType[] = [
	{
		id: 0,
		make: "Audi",
		year: "1965-",
		src: Audi,
		imgSize: "md",
		models: [
			{
				model: "Audi Q4 e-tron",
				image: Q4_e_tron,
				year: "2024",
				Desc: "Pricing: The Audi Q4 e-tron 45 has a Recommend Retail Price (RRP) of £49,915 and an On The Road Price (OTR) of £50,745. The OTR Price includes VAT, first year of VED, vehicle first registration fee, number plates and delivery. \n\nDrivetrain and Performance: The Audi Q4 e-tron 45 is a full electric vehicle (BEV). The maximum power of the Audi Q4 e-tron 45 is 210 kW (282 hp). The maximum torque is 402 lb-ft. The Audi Q4 e-tron 45 is rear wheel drive and can accelerate from 0 to 62 miles per hour in 6.7 seconds. The top speed is 112 mph. \n\nBattery and Charging: The battery of the Audi Q4 e-tron 45 has a total capacity of 82 kWh. The usable capacity is 77 kWh. An estimated range of about 260 miles is achievable on a fully charged battery. The actual range will however depend on several factors including climate, terrain, use of climate control systems and driving style. For example: sustaining high speeds in cold weather could result in a range of around 185 mi. However, driving at low speeds in mild weather will increase the range to around 380 mi. Charging is done using a Type 2 connector and the on-board charger has a maximum power of 11 kW. This charges a fully depleted battery back to full in around 8 hours 15 minutes. However, a 3-phase grid connection is needed to achieve this. The majority of homes and charge points currently do not have this connection. In most cases the maximum charging power will be 7.4 kW, allowing for a charge time of 12 hours 15 minutes and a charge rate of 21 mph. Charging the car using a regular wall plug will take around 39 hours 30 minutes. Rapid charging is possible through a CCS connection. The maximum rapid charge power is 135 kW. The battery can't be charged continuously at this power. In an average rapid charge session the average charge power will be around 120 kW. This charges the battery from 10% to 80% in around 30 minutes. A rapid charge like this will add about 180 miles of range. \n\nEnergy Consumption: The estimated combined (motorway and city) energy consumption of the Audi Q4 e-tron 45 is about 296 Wh per mile. By comparison, this energy consumption is the equivalent of a fuel consumption of 137 mpg in a traditional petrol car. The actual energy consumption will depend on several factors including climate, terrain, use of climate control systems and driving style. For example: sustaining high speeds in cold weather could result in an energy use of around 416 Wh per mile. However, driving at low speeds in mild weather will increase the efficiency to about 203 Wh per mile.",
				FuelType: electric,
				Power: "167-335 BHP",
			},
			{
				model: "Audi TTRS",
				image: TTRS_2023,
				year: "2023",
				Desc: "Pricing: The Audi TTRS starts at a base price of £65,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi TTRS is powered by a turbocharged 2.5-liter inline-five engine producing over 400 horsepower. It features Audi's legendary quattro all-wheel-drive system, delivering exceptional traction and agility. The TTRS can accelerate from 0 to 60 mph in just under 3.5 seconds, with a top speed electronically limited to 155 mph. Its sport-tuned suspension and precise steering provide exhilarating handling and control, making every drive a thrilling experience.",
				FuelType: fuel,
				Power: "400+ BHP",
			},
			{
				model: "Audi TTS",
				image: TTS_2021,
				year: "2021",
				Desc: "Pricing: The Audi TTS starts at a base price of £50,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi TTS is equipped with a turbocharged 2.0-liter four-cylinder engine producing around 300 horsepower. It features Audi's renowned quattro all-wheel-drive system, providing excellent traction and stability in all conditions. The TTS can accelerate from 0 to 60 mph in approximately 4.5 seconds, with a top speed electronically limited to 155 mph. Its sport-tuned suspension and responsive handling make it a joy to drive, offering a perfect balance of performance and comfort.",
				FuelType: fuel,
				Power: "300+ BHP",
			},
			{
				model: "Audi RS7",
				image: RS7_2023,
				year: "2023",
				Desc: "Pricing: The Audi RS7 starts at a base price of £110,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi RS7 is powered by a twin-turbocharged 4.0-liter V8 engine producing over 600 horsepower. It features Audi's quattro all-wheel-drive system and an eight-speed automatic transmission, delivering lightning-fast acceleration and precise handling. The RS7 can sprint from 0 to 60 mph in under 3.5 seconds, with a top speed electronically limited to 155 mph. Its adaptive air suspension and dynamic steering system provide exceptional ride comfort and agility, making it a true high-performance luxury sedan.",
				FuelType: fuel,
				Power: "600+ BHP",
			},
			{
				model: "Audi RS6 (C7, C8)",
				image: "RS6_image_url",
				year: "2023",
				Desc: "Pricing: The Audi RS6 starts at a base price of £90,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi RS6 is powered by a twin-turbocharged 4.0-liter V8 engine producing over 600 horsepower. It features Audi's quattro all-wheel-drive system and an eight-speed automatic transmission, delivering exhilarating acceleration and precise handling. The RS6 can accelerate from 0 to 60 mph in under 3.5 seconds, with a top speed electronically limited to 155 mph. Its adaptive air suspension and dynamic steering system provide exceptional ride comfort and agility, making it a top choice for performance enthusiasts and families alike.",
				FuelType: fuel,
				Power: "600+ BHP",
			},
			{
				model: "Audi RS5",
				image: "RS5_image_url",
				year: "2023",
				Desc: "Pricing: The Audi RS5 starts at a base price of £75,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi RS5 is equipped with a twin-turbocharged 2.9-liter V6 engine producing around 450 horsepower. It features Audi's quattro all-wheel-drive system and an eight-speed automatic transmission, delivering impressive performance and handling. The RS5 can accelerate from 0 to 60 mph in approximately 3.5 seconds, with a top speed electronically limited to 155 mph. Its sport-tuned suspension and responsive steering provide excellent agility and control, making it a thrilling sports coupe.",
				FuelType: fuel,
				Power: "450+ BHP",
			},
			{
				model: "Audi RS4 (B8, B9)",
				image: "RS4_image_url",
				year: "2023",
				Desc: "Pricing: The Audi RS4 starts at a base price of £70,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi RS4 is powered by a naturally aspirated 4.2-liter V8 engine producing around 450 horsepower. It features Audi's quattro all-wheel-drive system and a seven-speed dual-clutch automatic transmission, providing exhilarating performance and precise handling. The RS4 can accelerate from 0 to 60 mph in approximately 4.0 seconds, with a top speed electronically limited to 155 mph. Its sport-tuned suspension and advanced chassis technologies ensure exceptional agility and stability, making it a true high-performance sports sedan.",
				FuelType: fuel,
				Power: "450+ BHP",
			},
			{
				model: "Audi RS3",
				image: "RS3_image_url",
				year: "2023",
				Desc: "Pricing: The Audi RS3 starts at a base price of £50,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi RS3 is equipped with a turbocharged 2.5-liter inline-five engine producing around 400 horsepower. It features Audi's quattro all-wheel-drive system and a seven-speed dual-clutch automatic transmission, delivering impressive performance and agility. The RS3 can accelerate from 0 to 60 mph in approximately 3.5 seconds, with a top speed electronically limited to 155 mph. Its sport-tuned suspension and precise steering provide excellent handling and control, making it a top choice for enthusiasts.",
				FuelType: fuel,
				Power: "400+ BHP",
			},
			{
				model: "Audi S8 (D4, D5)",
				image: "S8_image_url",
				year: "2023",
				Desc: "Pricing: The Audi S8 starts at a base price of £90,000. Final pricing may vary depending on optional features and packages.\n\nDrivetrain and Performance: The Audi S8 is powered by a twin-turbocharged 4.0-liter V8 engine producing over 500 horsepower. It features Audi's quattro all-wheel-drive system and an eight-speed automatic transmission, delivering effortless acceleration and smooth power delivery. The S8 can accelerate from 0 to 60 mph in under 4.0 seconds, with a top speed electronically limited to 155 mph. Its adaptive air suspension and predictive active suspension system provide exceptional ride comfort and stability, making it a luxurious and high-performance executive sedan.",
				FuelType: fuel,
				Power: "500+ BHP",
			},
			{
				model: "Audi S7",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S6 (C7, C8)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S5",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S4 (B8, B9)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S3 (8V)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S1",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi TT (8J, 8S)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi Q8",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi Q7",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi Q5",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi Q3",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi Q2",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A8 (D4, D5)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A7",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A6 (C7, C8)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A5",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A4 (B8, B9)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A3 (8V)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A1",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi R8",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi RS6 Avant (C6)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi RS6 (C5)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi RS4 (B5, B7)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S8 (D3)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S6 (C5, C6)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S4 (B6, B7)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S3 (8L, 8P)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S3 (8L, 8P)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi TT (8N)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A8 (D3)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A6 (C5, C6)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A4 (B6, B7)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A3 (8L, 8P)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A2",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi RS2 Avant",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S8 (D2)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S6 (C4)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S4 (B5)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi S2",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi Cabriolet",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A8 (D2)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A6 (C4)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi A4 (B5)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi 100 (C4)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
			{
				model: "Audi 90 (B4)",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
		],
	},
	{
		id: 1,
		make: "Volkswagen",
		year: "1938-",
		src: VW,
		imgSize: "sm",
		models: [],
	},
	{
		id: 2,
		make: "Bmw",
		year: "1927-",
		src: BMW,
		imgSize: "sm",
		models: [
			{
				model: "BMW 3 Series",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
		],
	},
	{
		id: 3,
		make: "Toyota",
		year: "1936-",
		src: Toyota,
		imgSize: "sm",
		models: [
			{
				model: "Toyota Yaris",
				image: "",
				year: "",
				Desc: "",
				FuelType: "",
				Power: "",
			},
		],
	},
	{
		id: 4,
		make: "Ford",
		year: "1903-",
		src: Ford,
		imgSize: "md",
		models: [],
	},
	{
		id: 5,
		make: "Mercedes",
		year: "1926-",
		src: Mercedes,
		imgSize: "sm",
		models: [],
	},
	{
		id: 6,
		make: "Volvo",
		year: "1927-",
		src: Volvo,
		imgSize: "sm",
		models: [],
	},
	{
		id: 7,
		make: "Skoda",
		year: "1934-",
		src: Skoda,
		imgSize: "sm",
		models: [],
	},
	{
		id: 8,
		make: "Vauxhall",
		year: "1933-",
		src: Vauxhall,
		imgSize: "sm",
		models: [],
	},
	{
		id: 9,
		make: "Honda",
		year: "1949-",
		src: Honda,
		imgSize: "sm",
		models: [],
	},
	{
		id: 10,
		make: "Seat",
		year: "1963-",
		src: Seat,
		imgSize: "sm",
		models: [],
	},
	{
		id: 10,
		make: "Cupra",
		year: "2018-",
		src: Cupra,
		imgSize: "md",
		models: [],
	},
];
